#!/bin/bash

# this file is only slightly modified from source files at https://github.com/jmanuoz/Measuring-controversy-in-Social-Networks-through-NLP

declare -a scores
scores=()
Rscript create_txt.R $@
python fast_text_py.py $@

scores+=($(python3 score.py $@))
echo "Scores"
printf '%s \n' "${scores[@]}"
